### ISSUE TITLE
Invalid JavaScript

### ISSUE THREAD

**Issue by locks** [glimmerjs/resolution-map-builder#17]
Someone mentioned that the build pipeline errored because they had a `template.hbs` and a `.template.hbs` (notice the leading dot) file in the same folder due to vim.
@rwjblue said that we generate invalid JavaScript and it should be reported in this repository.

**Comment by rwjblue** [comment]
The invalid JS comes from [here](https://github.com/glimmerjs/resolution-map-builder/blob/2b798b4f42ab1cff527c9421a72a1d29557d0fd5/lib/index.js#L87-L88), we don't account for filenames that have anything other than `/` or `-` in the name.  We should probably replace any non-word char instead.

However, the real underlying issue is a more interesting point, I do not think that the `.template.hbs` should actually attempt to end up in the module map at all.  

@dgeb - Do you think we should ignore files that start with a `.` (similar to how we ignore `.md` / `.html` files)?
